/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  docs: [
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'guide/introduction',
        'guide/roadmap',
        'guide/ecosystem',
        'guide/community',
        'guide/partnership',
      ],
    },
    {
      type: 'category',
      label: 'Products',
      link: {
        type: 'generated-index',
        description: "RSS3 offers multiple products to help you build the feed of Web3."
      },
      collapsed: false,
      items: [
        'product/network',
        {
          type: 'category',
          label: 'PreGod',
          link: {
            type: 'generated-index',
            description: "PreGod provides a set of powerful yet simple-to-use APIs to access the feed of Web3.",
          },
          collapsed: false,
          items: [
            'product/PreGod/introduction',
            {
              // TODO: update API link
              type: 'link',
              label: 'API Playground',
              href: '/api',
            },
            {
              type: 'category',
              label: 'Tutorial',
              link: {
                type: 'generated-index',
                description: "Some tutorials to help you get started with PreGod.",
              },
              collapsed: true,
              items: [
                'product/PreGod/Tutorials/cookbook',
                'product/PreGod/Tutorials/mirror_reader',
                'product/PreGod/Tutorials/improving_feed_granularity',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Misc',
      link: {
        type: 'generated-index',
      },
      items: [
        'misc/branding',
        'misc/faq',
      ],
    },
    'support',
  ]

};

module.exports = sidebars;
